### PR TITLE
Fix build of v1.1.0

### LINKED ISSUE #106: Can not build v1.1.0
```
[ 45%] Building CXX object src/nx/xml/CMakeFiles/xml_objects.dir/node.cpp.o
/libpniio/src/nx/xml/node.cpp: In function 'bool pni::io::nx::xml::has_attribute(const node&, const string&)':
/libpniio/src/nx/xml/node.cpp:125:16: error: cannot convert 'boost::optional<const boost::property_tree::basic_ptree<std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char> >&>' to 'bool' in return                                                                                                                                                                          
         return attr;                                                                                                                                                                        
                ^~~~                                                                                                                                                                         
In file included from /usr/include/boost/property_tree/detail/xml_parser_utils.hpp:15:0,                                                                                                     
                 from /usr/include/boost/property_tree/detail/xml_parser_write.hpp:15,                                                                                                       
                 from /usr/include/boost/property_tree/xml_parser.hpp:15,                                                                                                                    
                 from /libpniio/src/nx/xml/node.cpp:26:                                                                                                                                      
/usr/include/boost/property_tree/detail/xml_parser_writer_settings.hpp: In instantiation of 'class boost::property_tree::xml_parser::xml_writer_settings<char>':                             
/libpniio/src/nx/xml/node.cpp:131:65:   required from here                                                                                                                                   
/usr/include/boost/property_tree/detail/xml_parser_writer_settings.hpp:38:42: error: 'char' is not a class, struct, or union type                                                            
         typedef typename Str::value_type Ch;                                                                                                                                                
                                          ^~                                                                                                                                                 
/usr/include/boost/property_tree/detail/xml_parser_writer_settings.hpp:40:9: error: 'char' is not a class, struct, or union type                                                             
         xml_writer_settings(Ch inchar = Ch(' '),                                                                                                                                            
         ^~~~~~~~~~~~~~~~~~~
/usr/include/boost/property_tree/detail/xml_parser_writer_settings.hpp:50:33: error: 'char' is not a class, struct, or union type
         typename Str::size_type indent_count;
                                 ^~~~~~~~~~~~
/libpniio/src/nx/xml/node.cpp: In function 'std::ostream& pni::io::nx::xml::operator<<(std::ostream&, const node&)':
/libpniio/src/nx/xml/node.cpp:131:72: error: no matching function for call to 'boost::property_tree::xml_parser::xml_writer_settings<char>::xml_writer_settings(char, int)'
         boost::property_tree::xml_writer_settings<char> settings('\t',1);
                                                                        ^
In file included from /usr/include/boost/property_tree/detail/xml_parser_utils.hpp:15:0,
                 from /usr/include/boost/property_tree/detail/xml_parser_write.hpp:15,
                 from /usr/include/boost/property_tree/xml_parser.hpp:15,
                 from /libpniio/src/nx/xml/node.cpp:26:
/usr/include/boost/property_tree/detail/xml_parser_writer_settings.hpp:36:11: note: candidate: boost::property_tree::xml_parser::xml_writer_settings<char>::xml_writer_settings()
     class xml_writer_settings
           ^~~~~~~~~~~~~~~~~~~
/usr/include/boost/property_tree/detail/xml_parser_writer_settings.hpp:36:11: note:   candidate expects 0 arguments, 2 provided
/usr/include/boost/property_tree/detail/xml_parser_writer_settings.hpp:36:11: note: candidate: constexpr boost::property_tree::xml_parser::xml_writer_settings<char>::xml_writer_settings(const boost::property_tree::xml_parser::xml_writer_settings<char>&)
/usr/include/boost/property_tree/detail/xml_parser_writer_settings.hpp:36:11: note:   candidate expects 1 argument, 2 provided
/usr/include/boost/property_tree/detail/xml_parser_writer_settings.hpp:36:11: note: candidate: constexpr boost::property_tree::xml_parser::xml_writer_settings<char>::xml_writer_settings(boost::property_tree::xml_parser::xml_writer_settings<char>&&)
/usr/include/boost/property_tree/detail/xml_parser_writer_settings.hpp:36:11: note:   candidate expects 1 argument, 2 provided
/libpniio/src/nx/xml/node.cpp:133:53: error: no matching function for call to 'write_xml(std::ostream&, const node&, boost::property_tree::xml_parser::xml_writer_settings<char>&)'
         boost::property_tree::write_xml(o,n,settings);
                                                     ^
In file included from /libpniio/src/nx/xml/node.cpp:26:0:
/usr/include/boost/property_tree/xml_parser.hpp:124:10: note: candidate: template<class Ptree> void boost::property_tree::xml_parser::write_xml(const string&, const Ptree&, const std::locale&, const boost::property_tree::xml_parser::xml_writer_settings<typename Ptree::key_type>&)
     void write_xml(const std::string &filename,
          ^~~~~~~~~
/usr/include/boost/property_tree/xml_parser.hpp:124:10: note:   template argument deduction/substitution failed:
/libpniio/src/nx/xml/node.cpp:133:41: note:   cannot convert 'o' (type 'std::ostream {aka std::basic_ostream<char>}') to type 'const string& {aka const std::__cxx11::basic_string<char>&}'
         boost::property_tree::write_xml(o,n,settings);
                                         ^
In file included from /libpniio/src/nx/xml/node.cpp:26:0:
/usr/include/boost/property_tree/xml_parser.hpp:100:10: note: candidate: void boost::property_tree::xml_parser::write_xml(std::basic_ostream<typename Ptree::key_type::value_type>&, const Ptree&, const boost::property_tree::xml_parser::xml_writer_settings<typename Ptree::key_type>&) [with Ptree = boost::property_tree::basic_ptree<std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char> >; typename Ptree::key_type::value_type = char; typename Ptree::key_type = std::__cxx11::basic_string<char>]
     void write_xml(std::basic_ostream<
          ^~~~~~~~~
/usr/include/boost/property_tree/xml_parser.hpp:100:10: note:   no known conversion for argument 3 from 'boost::property_tree::xml_parser::xml_writer_settings<char>' to 'const boost::property_tree::xml_parser::xml_writer_settings<std::__cxx11::basic_string<char> >&'
make[2]: *** [src/nx/xml/CMakeFiles/xml_objects.dir/node.cpp.o] Error 1
src/nx/xml/CMakeFiles/xml_objects.dir/build.make:86: recipe for target 'src/nx/xml/CMakeFiles/xml_objects.dir/node.cpp.o' failed
make[1]: *** [src/nx/xml/CMakeFiles/xml_objects.dir/all] Error 2
CMakeFiles/Makefile2:1547: recipe for target 'src/nx/xml/CMakeFiles/xml_objects.dir/all' failed
make: *** [all] Error 2
Makefile:138: recipe for target 'all' failed
The command '/bin/sh -c make install' returned a non-zero code: 2
```

CMake output:

```
-- The C compiler identification is GNU 6.3.0
-- The CXX compiler identification is GNU 6.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
No build type specified - default is RELEASE
-- Boost version: 1.62.0
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29") 
-- HDF5: Using hdf5 compiler wrapper to determine C configuration
-- Found HDF5: /usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5.so;/usr/lib/x86_64-linux-gnu/libpthread.so;/usr/lib/x86_64-linux-gnu/libsz.so;/usr/lib/x86_64-linux-gnu/libz.so;/usr/lib/x86_64-linux-gnu/libdl.so;/usr/lib/x86_64-linux-gnu/libm.so (found version "1.10.0.1")  
found GNU compiler ...
setup for release build ...                                                                                                                                                                  
3.7.2                                                                                                                                                                                        
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of uint8_t
-- Check size of uint8_t - done
-- Check size of int8_t
-- Check size of int8_t - done
-- Check size of uint16_t
-- Check size of uint16_t - done
-- Check size of int16_t
-- Check size of int16_t - done
-- Check size of uint32_t
-- Check size of uint32_t - done
-- Check size of int32_t
-- Check size of int32_t - done
-- Check size of uint64_t
-- Check size of uint64_t - done
-- Check size of int64_t
-- Check size of int64_t - done
-- Check size of float
-- Check size of float - done
-- Check size of double
-- Check size of double - done
-- Check size of long double
-- Check size of long double - done
-- Checking for one of the modules 'pnicore'
-- Boost version: 1.62.0
-- Found the following Boost libraries:
--   program_options
--   system
--   regex
--   unit_test_framework
-- Checking for one of the modules 'cppunit'
/usr/include/hdf5/serial
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
CMake Warning (dev) at test/xml_test/io_node/CMakeLists.txt:8 (configure_file):
  configure_file called with unknown argument(s):                                                                                                                                            

   COPY_ONLY                                                                                                                                                                                 

This warning is for project developers.  Use -Wno-dev to suppress it.                                                                                                                        

CMake Warning (dev) at test/xml_test/io_node/CMakeLists.txt:8 (configure_file):                                                                                                              
  configure_file called with unknown argument(s):                                                                                                                                            

   COPY_ONLY                                                                                                                                                                                 

This warning is for project developers.  Use -Wno-dev to suppress it.                                                                                                                        

CMake Warning (dev) at test/xml_test/io_node/CMakeLists.txt:8 (configure_file):                                                                                                              
  configure_file called with unknown argument(s):                                                                                                                                            

   COPY_ONLY                                                                                                                                                                                 

This warning is for project developers.  Use -Wno-dev to suppress it.                                                                                                                        

-- generate scalar attribute test for type uint8 ...
-- Set flags for main file...
-- generate scalar attribute test for type int8 ...
-- generate scalar attribute test for type uint16 ...
-- generate scalar attribute test for type int16 ...
-- generate scalar attribute test for type uint32 ...
-- generate scalar attribute test for type int32 ...
-- generate scalar attribute test for type uint64 ...
-- generate scalar attribute test for type int64 ...
-- generate scalar attribute test for type float32 ...
-- generate scalar attribute test for type float64 ...
-- generate scalar attribute test for type float128 ...
-- setup for float128 comparison
CMake Warning (dev) at test/xml_test/attribute/CMakeLists.txt:50 (set):
  Policy CMP0053 is not set: Simplify variable reference and escape sequence                                                                                                                 
  evaluation.  Run "cmake --help-policy CMP0053" for policy details.  Use the                                                                                                                
  cmake_policy command to set the policy and suppress this warning.                                                                                                                          

  For input:                                                                                                                                                                                 

    'BOOST_CHECK_CLOSE(@TYPE@(data),expected,1.e-14);'                                                                                                                                       

  the old evaluation rules produce:                                                                                                                                                          

    'BOOST_CHECK_CLOSE(float128(data),expected,1.e-14);'                                                                                                                                     

  but the new evaluation rules produce:                                                                                                                                                      

    'BOOST_CHECK_CLOSE(@TYPE@(data),expected,1.e-14);'                                                                                                                                       

  Using the old result for compatibility since the policy is not set.                                                                                                                        
This warning is for project developers.  Use -Wno-dev to suppress it.                                                                                                                        

-- generate scalar attribute test for type complex32 ...
-- generate scalar attribute test for type complex64 ...
-- generate scalar attribute test for type complex128 ...
-- setup for complex128 comnparison
-- generate scalar attribute test for type string ...
-- generate scalar attribute test for type bool_t ...
-- generate array attribute test for type uint8 ...
-- generate array attribute test for type int8 ...
-- generate array attribute test for type uint16 ...
-- generate array attribute test for type int16 ...
-- generate array attribute test for type uint32 ...
-- generate array attribute test for type int32 ...
-- generate array attribute test for type uint64 ...
-- generate array attribute test for type int64 ...
-- generate array attribute test for type float32 ...
-- generate array attribute test for type float64 ...
-- generate array attribute test for type float128 ...
-- setup for float128 comparison
CMake Warning (dev) at test/xml_test/attribute/CMakeLists.txt:126 (set):
  Policy CMP0053 is not set: Simplify variable reference and escape sequence                                                                                                                 
  evaluation.  Run "cmake --help-policy CMP0053" for policy details.  Use the                                                                                                                
  cmake_policy command to set the policy and suppress this warning.                                                                                                                          

  For input:                                                                                                                                                                                 

    'BOOST_CHECK_CLOSE(@TYPE@(*d_iter),*r_iter,1.e-14);'                                                                                                                                     

  the old evaluation rules produce:                                                                                                                                                          

    'BOOST_CHECK_CLOSE(float128(*d_iter),*r_iter,1.e-14);'                                                                                                                                   

  but the new evaluation rules produce:                                                                                                                                                      

    'BOOST_CHECK_CLOSE(@TYPE@(*d_iter),*r_iter,1.e-14);'                                                                                                                                     

  Using the old result for compatibility since the policy is not set.                                                                                                                        
This warning is for project developers.  Use -Wno-dev to suppress it.                                                                                                                        

-- generate array attribute test for type complex32 ...
-- generate array attribute test for type complex64 ...
-- generate array attribute test for type complex128 ...
-- setup for complex128 comnparison
-- generate array attribute test for type bool_t ...
-- generate scalar field test for type uint8 ...
-- generate scalar field test for type int8 ...
-- generate scalar field test for type uint16 ...
-- generate scalar field test for type int16 ...
-- generate scalar field test for type uint32 ...
-- generate scalar field test for type int32 ...
-- generate scalar field test for type uint64 ...
-- generate scalar field test for type int64 ...
-- generate scalar field test for type float32 ...
-- generate scalar field test for type float64 ...
-- generate scalar field test for type float128 ...
-- generate scalar field test for type complex32 ...
-- generate scalar field test for type complex64 ...
-- generate scalar field test for type complex128 ...
-- generate scalar field test for type string ...
-- generate scalar field test for type bool_t ...
-- generate array field test for type uint8 ...
-- generate array field test for type int8 ...
-- generate array field test for type uint16 ...
-- generate array field test for type int16 ...
-- generate array field test for type uint32 ...
-- generate array field test for type int32 ...
-- generate array field test for type uint64 ...
-- generate array field test for type int64 ...
-- generate array field test for type float32 ...
-- generate array field test for type float64 ...
-- generate array field test for type float128 ...
-- generate array field test for type complex32 ...
-- generate array field test for type complex64 ...
-- generate array field test for type complex128 ...
-- generate array field test for type bool_t ...
CMake Warning (dev) at test/xml_test/link/CMakeLists.txt:8 (configure_file):
  configure_file called with unknown argument(s):                                                                                                                                            

   COPY_ONLY                                                                                                                                                                                 

This warning is for project developers.  Use -Wno-dev to suppress it.                                                                                                                        

CMake Warning (dev) at test/xml_test/link/CMakeLists.txt:8 (configure_file):                                                                                                                 
  configure_file called with unknown argument(s):                                                                                                                                            

   COPY_ONLY                                                                                                                                                                                 

This warning is for project developers.  Use -Wno-dev to suppress it.                                                                                                                        

-- Configuring done
CMake Warning (dev) at src/CMakeLists.txt:35 (add_dependencies):
  Policy CMP0046 is not set: Error on non-existent dependency in                                                                                                                             
  add_dependencies.  Run "cmake --help-policy CMP0046" for policy details.                                                                                                                   
  Use the cmake_policy command to set the policy and suppress this warning.                                                                                                                  

  The dependency target "config.hpp" of target "pniio" does not exist.                                                                                                                       
This warning is for project developers.  Use -Wno-dev to suppress it.                                                                                                                        

-- Generating done
-- Build files have been written to: /libpniio/build
```

### PR DESCRIPTION
**Pull request by Ingvord**
Fix #106 

Please merge into branch rooted from v1.1.0

### CODE REVIEW

**Comment by jkotan** [comment]
Could you explain me why you do it. The version v1.1.0 is already tagged. Add the fixes for this branch are in v1.1.1. If you have any fixes to v1.1.1 we can create PR and tag it as v1.1.2. We are not going to release v1.1.0 again and again. That does not make sense.   Could you please try to switch to a newer version.

**Comment by Ingvord** [comment]
@jkotan if we take DESY debian 9 env - it has only 1.1.0 installed:

```
khokhria@hzgxenvtest:~/bin/HeadQuarter$ aptitude search pniio
i A libpniio1.1.0                                                                          - PNI IO library - library binaries                                                               
p   libpniio1.1.0-dbg                                                                      - PNI IO library - debuging symbols                                                               
p   libpniio1.1.0-dev                                                                      - PNI IO library - development files                                                              
i   libpniio1.1.0-doc                                                                      - PNI IO library - documentation                                                                  
i   libpniio1.2.0                                                                          - PNI IO library - library binaries                                                               
p   libpniio1.2.0-dbg                                                                      - PNI IO library - debugging symbols                                                              
p   libpniio1.2.0-dev                                                                      - PNI IO library - development files                                                              
i   libpniio1.2.2                                                                          - PNI IO library - library binaries                                                               
p   libpniio1.2.2-dbg                                                                      - PNI IO library - debugging symbols                                                              
p   libpniio1.2.2-dev                                                                      - PNI IO library - development files
...
```

I need to rebuild my jni wrapper for 1.1.0. If I do it with 1.1.1 - ldd does not find so file in the production

**Comment by jkotan** [comment]
Now, you should be able to install 
```
i   libpniio1.1.1                                                          - PNI IO library - library binaries                                               
p   libpniio1.1.1-dbg                                                      - PNI IO library - debuging symbols                                               
p   libpniio1.1.1-dev                                                      - PNI IO library - development files                                              
p   libpniio1.1.1-doc                                                      - PNI IO library - documentation     
```
on hzgxenvtest.

Be aware that `libpniio1.1.1-dev` should be used with `libpnicore1.1.0-dev`.
Have a try :)

BTW, we are on the way to start migration from stretch to buster.

**Comment by jkotan** [comment]
Have you tried to use libpniio-1.2.8 and h5cpp0.3.3 ?
One year ago we decided to drop support for libpniio-1.1.*

**Comment by Ingvord** [comment]
> Have you tried to use libpniio-1.2.8 and h5cpp0.3.3 ?

Yes. Unfortunately, neither is compatible with our current system...

**Comment by jkotan** [comment]
What do you mean by "neither is compatible with our current system..."
Is it only API change or something deeper?

You can uses either `h5cpp` or both together `pninio` `h5cpp`

**Comment by Ingvord** [comment]
> Is it only API change or something deeper?

Both, I tried to fix API difference, but then I got new exceptions types from places where we had no problems before (and in case jni this simply kills our Tango server - not good). So it requires quite an effort to migrate.

> You can uses either h5cpp or both together pninio h5cpp

Thanks for the advise! We will definitely give it a try eventually!

**Comment by jkotan** [comment]
If you notice any bug related to  new pniio or h5cpp do not hesitate to report it

**Pull request closed without merging**
